export const CONFIG_DEFAULTS = {
  DEFAULT_SKIP_CREDIT_CAP_PERCENT: 25,
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  DAILY_MENU_CACHE_TTL_SECONDS: 15,
  DEFAULT_SEARCH_RADIUS_METERS: 5000,
  LAUNCH_CITY_NAME: 'Indore',
  DEFAULT_COMMISSION_PERCENTAGE: '14.00',
  ENABLE_MESS_SWITCH: false,
  ENABLE_AUTO_RENEW: false,
  ENABLE_CITY_CONFIG_UI: false
} as const;

