export const CONFIG_DEFAULTS = {
  DEFAULT_SKIP_CREDIT_CAP_PERCENT: 25,
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  DAILY_MENU_CACHE_TTL_SECONDS: 15,
  DEFAULT_SEARCH_RADIUS_METERS: 5000,
  DEFAULT_COMMISSION_PERCENTAGE: '10.00'
} as const;
