export enum ErrorCode {
  // Auth & Permissions
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  MOCK_AUTH_DISABLED = 'MOCK_AUTH_DISABLED',

  // Validation & Input
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',

  // Orders & Capacity
  CAPACITY_EXCEEDED = 'CAPACITY_EXCEEDED',
  CUTOFF_PASSED = 'CUTOFF_PASSED',
  CAPACITY_BELOW_PLACED_ORDERS = 'CAPACITY_BELOW_PLACED_ORDERS',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  ORDER_ALREADY_ACCEPTED = 'ORDER_ALREADY_ACCEPTED',
  ORDER_CANNOT_BE_CANCELLED = 'ORDER_CANNOT_BE_CANCELLED',

  // Subscriptions
  NO_SKIP_CREDITS = 'NO_SKIP_CREDITS',
  OVERLAPPING_PAUSE = 'OVERLAPPING_PAUSE',
  SUBSCRIPTION_NOT_ACTIVE = 'SUBSCRIPTION_NOT_ACTIVE',
  PLAN_NOT_FOUND = 'PLAN_NOT_FOUND',
  INVALID_PAUSE_DATES = 'INVALID_PAUSE_DATES',

  // Payments & Wallet
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  INSUFFICIENT_WALLET_BALANCE = 'INSUFFICIENT_WALLET_BALANCE',
  INVALID_WEBHOOK_SIGNATURE = 'INVALID_WEBHOOK_SIGNATURE',
  ALREADY_PROCESSED = 'ALREADY_PROCESSED',

  // Delivery
  INVALID_OTP = 'INVALID_OTP',
  DELIVERY_NOT_ASSIGNED = 'DELIVERY_NOT_ASSIGNED',
  DELIVERY_ALREADY_COMPLETED = 'DELIVERY_ALREADY_COMPLETED',

  // Reviews
  REVIEW_ALREADY_EXISTS = 'REVIEW_ALREADY_EXISTS',
  CANNOT_REVIEW_MESS = 'CANNOT_REVIEW_MESS',

  // Server
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
}
